# Generated by Django 4.2.6 on 2023-11-15 06:23

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('G', 'General'), ('R', 'Required'), ('C', 'Core'), ('O', 'Optional')], max_length=1)),
                ('unit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('exam_location', models.CharField(blank=True, max_length=30, null=True)),
                ('class_days', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=15, null=True)),
                ('class_end_time', models.TimeField(blank=True, null=True)),
                ('class_start_time', models.TimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('approved_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.approvedcourse')),
            ],
        ),
    ]
