# Generated by Django 4.2.6 on 2023-11-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('General', 'General'), ('Required', 'Required'), ('Core', 'Core'), ('Optional', 'Optional')], max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('corequisite', models.ManyToManyField(to='course.approvedcourse')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('prerequisite', models.ManyToManyField(to='course.approvedcourse')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateTimeField()),
                ('exam_location', models.CharField(blank=True, max_length=30, null=True)),
                ('class_days', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=15)),
                ('class_end_time', models.TimeField()),
                ('class_start_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('approved_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.approvedcourse')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professor')),
            ],
        ),
    ]
