# Generated by Django 4.2.6 on 2023-11-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedcourse',
            name='corequisite',
            field=models.ManyToManyField(null=True, to='course.approvedcourse'),
        ),
        migrations.AlterField(
            model_name='approvedcourse',
            name='prerequisite',
            field=models.ManyToManyField(null=True, to='course.approvedcourse'),
        ),
    ]
