# Generated by Django 4.2.6 on 2023-11-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('user', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercourse',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.professor'),
        ),
        migrations.AddField(
            model_name='approvedcourse',
            name='corequisite',
            field=models.ManyToManyField(blank=True, related_name='coapprovedcourse', to='course.approvedcourse'),
        ),
        migrations.AddField(
            model_name='approvedcourse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AddField(
            model_name='approvedcourse',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, related_name='preapprovedcourse', to='course.approvedcourse'),
        ),
    ]
