# Generated by Django 4.2.7 on 2023-11-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_supervisor'),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestercourse',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.professor'),
        ),
    ]
