# Generated by Django 4.2.6 on 2023-11-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_approvedcourse_corequisite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedcourse',
            name='corequisite',
            field=models.ManyToManyField(related_name='+', to='course.approvedcourse'),
        ),
        migrations.AlterField(
            model_name='approvedcourse',
            name='prerequisite',
            field=models.ManyToManyField(related_name='+', to='course.approvedcourse'),
        ),
    ]
