# Generated by Django 4.2.6 on 2023-11-01 12:09

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('course', '0007_alter_approvedcourse_corequisite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestercourse',
            name='class_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='class_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='class_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.professor'),
        ),
    ]
