# Generated by Django 4.2.6 on 2023-11-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_semestercourse_class_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvedcourse',
            old_name='credit',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='approvedcourse',
            name='corequisite',
            field=models.ManyToManyField(blank=True, related_name='coapprovedcourse', to='course.approvedcourse'),
        ),
        migrations.AlterField(
            model_name='approvedcourse',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, related_name='preapprovedcourse', to='course.approvedcourse'),
        ),
        migrations.AlterField(
            model_name='approvedcourse',
            name='type',
            field=models.CharField(choices=[('G', 'General'), ('R', 'Required'), ('C', 'Core'), ('O', 'Optional')], max_length=1),
        ),
    ]
