# Generated by Django 4.2.7 on 2023-11-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitRegisterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_answer', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_register_request', to='user.student')),
                ('termic_course', models.ManyToManyField(related_name='unit_register_request', to='course.semestercourse')),
            ],
        ),
    ]
