# Generated by Django 4.2.7 on 2023-11-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_selection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitregisterrequest',
            old_name='termic_course',
            new_name='semester_course',
        ),
        migrations.AlterField(
            model_name='unitregisterrequest',
            name='request_answer',
            field=models.BooleanField(choices=[('A', 'accepted'), ('D', 'decline'), ('P', 'pending')], default='P', max_length=1),
        ),
    ]
