# Generated by Django 4.2.7 on 2023-11-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_selection', '0002_rename_termic_course_unitregisterrequest_semester_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitregisterrequest',
            name='request_answer',
            field=models.CharField(choices=[('A', 'accepted'), ('D', 'decline'), ('P', 'pending')], default='P', max_length=1),
        ),
    ]
