# Generated by Django 4.2.7 on 2023-11-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_semestercourse_professor'),
        ('course_selection', '0003_alter_studentcourse_score_studentsemester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsemester',
            name='courses',
        ),
        migrations.AlterField(
            model_name='studentsemester',
            name='sum_of_unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentsemester',
            name='courses',
            field=models.ManyToManyField(to='course.semestercourse'),
        ),
    ]
