# Generated by Django 4.2.7 on 2023-11-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_selection', '0004_remove_studentsemester_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsemester',
            old_name='semester_no',
            new_name='term_no',
        ),
    ]
