# Generated by Django 4.2.7 on 2023-11-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_term_semester_code'),
        ('course_selection', '0005_rename_semester_no_studentsemester_term_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitregisterrequest',
            name='semester_code',
            field=models.ForeignKey(default=14021, on_delete=django.db.models.deletion.DO_NOTHING, to='university.term'),
            preserve_default=False,
        ),
    ]
