# Generated by Django 4.2.7 on 2023-11-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_semestercourse_professor'),
        ('course_selection', '0006_unitregisterrequest_semester_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsemester',
            name='courses',
            field=models.ManyToManyField(blank=True, to='course.semestercourse'),
        ),
    ]
