# Generated by Django 4.2.7 on 2023-11-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Passed_Courses',
            field=models.ManyToManyField(related_name='student_passed_course', to='course.approvedcourse'),
        ),
        migrations.AddField(
            model_name='student',
            name='Passing_Courses',
            field=models.ManyToManyField(related_name='student_passing_course', to='course.semestercourse'),
        ),
    ]
