# Generated by Django 4.2.6 on 2023-11-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passed_courses',
            field=models.ManyToManyField(blank=True, to='course.approvedcourse'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passing_courses',
            field=models.ManyToManyField(blank=True, to='course.semestercourse'),
        ),
    ]
