# Generated by Django 4.2.7 on 2023-11-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passed_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_passed_course', to='course.approvedcourse'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passing_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_passing_course', to='course.semestercourse'),
        ),
    ]
