# Generated by Django 4.2.7 on 2023-11-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_passed_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
