# Generated by Django 4.2.7 on 2023-11-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_academic_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='academic_years',
            new_name='academic_terms',
        ),
    ]
