# Generated by Django 4.2.7 on 2023-11-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_new_student',
            field=models.BooleanField(default=True),
        ),
    ]
