# Generated by Django 4.2.6 on 2023-11-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_passed_courses_student_passing_courses'),
        ('user', '0004_rename_academic_years_student_academic_terms'),
    ]

    operations = [
    ]
