# Generated by Django 4.2.6 on 2023-11-06 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20231106_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_terms',
        ),
    ]
