# Generated by Django 4.2.7 on 2023-11-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('semester_code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('start_date_unit_selection', models.DateTimeField()),
                ('end_date_unit_selection', models.DateTimeField()),
                ('start_date_class', models.DateTimeField()),
                ('end_date_class', models.DateTimeField()),
                ('start_date_rechoice', models.DateTimeField()),
                ('end_date_rechoice', models.DateTimeField()),
                ('start_date_of_w', models.DateField()),
                ('end_date_of_w', models.DateField()),
                ('start_date_of_delete_semester', models.DateField()),
                ('end_date_of_delete_semester', models.DateField()),
                ('start_date_of_exams', models.DateField()),
                ('end_date_of_exams', models.DateField()),
                ('course', models.ManyToManyField(to='course.approvedcourse')),
            ],
        ),
    ]
