# Generated by Django 4.2.7 on 2023-11-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='lecturers',
            field=models.ManyToManyField(to='user.professor'),
        ),
        migrations.AddField(
            model_name='term',
            name='students',
            field=models.ManyToManyField(to='user.student'),
        ),
    ]
