# Generated by Django 4.2.7 on 2023-11-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='semester_code',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
