# Generated by Django 4.2.7 on 2023-11-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_term_semester_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='semester_code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
